#!/bin/bash

VERSION=`cat VERSION`

echo "Build hook for $DOCKER_REPO running"
echo "Version: $VERSION"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BUILD_VERSION=$VERSION \
             -t $DOCKER_REPO:$VERSION \
             -t $DOCKER_REPO:latest \
             .
